version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: zf2_app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 start_with_request=yes
      PHP_IDE_CONFIG: serverName=zf2

volumes:
  db_data:
